version: '3.7'

services:

  flask-microservice:
    container_name: flask-microservice
    build:
      context: ../../flask-microservice/app
      dockerfile: Dockerfile-local
    ports:
      - 8000:5000
    environment:
        - FLASK_ENV=development

  react-microservice:
    container_name: react-microservice
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3000:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    links:
      - flask-microservice


